### ISSUE TITLE
How to get the contrib/plugins/libips.so?

### ISSUE THREAD

**Issue by tgonzalez89** [donno2048/snake-bios#2]
The instructions to run on qemu are a bit incomplete. I installed qemu in Ubuntu (sudo apt install qemu-system), but I don't where to get the plugin you mention in the README (contrib/plugins/libips.so). I don't find that installed in Ubuntu. I see it in the qemu source code (https://github.com/qemu/qemu/tree/master/contrib/plugins). Did you compile it yourself? If so, can you share how? I guess you'd have to cross compile it to x86 instead of 64-bit.

**Comment by donno2048** [comment]
Yeah, you'd have to build QEMU from source, for some reason they won't ship the plugins in the install package... 😕 You can follow the instructions for your machine just don't forget to do `./configure --target-list=i386-softmmu --enable-curses --enable-plugins` and then `make all` to make both the binary and the plugin.

I would also suggest `--disable-docs` to save some compile time.

**Comment by donno2048** [comment]
Didn't check but pretty sure that would work:


```sh
git clone --branch stable-9.2 --depth 1 https://github.com/qemu/qemu
cd qemu
./configure --target-list=i386-softmmu --enable-curses --enable-plugins --disable-docs
make all
```

**Comment by tgonzalez89** [comment]
Awesome. That worked. Thanks!
